[package]
name = "toon-vulkano"
version = "0.1.0"
edition = "2021"

[dependencies]
default = "0.1.2"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.7"
rand = "0.8.5"

[profile.dev]
opt-level = 1
