[package]
name = "toon-vulkano"
version = "0.1.0"
edition = "2021"

[dependencies]
default = "0.1.2"
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
winit = { version = "0.28.7"} # , features = ["rwh_05"]
rand = "0.8.5"
colored = "2"
cgmath = "0.18.0"

[profile.dev]
opt-level = 1
